# config.yaml
name: "Dienstplan KI Parser"
version: "1.0.3"
slug: "dienstplan_ki_parser"
description: "Erkennt automatisch Schichtpläne anhand eines Bildes"
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7
