name: Dienstplan KI Parser (ONNX)
version: "1.0.0"
slug: dienstplan_ki_parser
description: Erkennung von Schichtcodes im Dienstplanbild per KI (ONNX)
startup: services
boot: auto
homeassistant_api: false
host_network: false
options: {}
schema: {}
