name: Dienstplan KI Parser
version: 1.0.123
slug: dienstplan_ki_parser
description: Dienstplanerkennung mit YOLO und ICS-Export
arch:
  - amd64
  - aarch64
startup: application
boot: manual
init: false
options: {}
schema: {}
