name: "Dienstplan KI Parser"
version: "1.0.1"
slug: "dienstplan_ki_parser"
description: "Verarbeitet Dienstpläne aus Bildern automatisch mit KI"
arch:
  - aarch64
  - armv7
  - amd64
startup: application
boot: auto
host_network: true
options: {}
schema: {}
